# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('glory', models.IntegerField(default=0)),
                ('cooldown', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('members', models.ManyToManyField(to='gm.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger_time', models.DateTimeField(blank=True, null=True)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=200)),
                ('glory_on_success', models.IntegerField()),
                ('glory_on_failure', models.IntegerField()),
                ('showdown', models.NullBooleanField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('cooldown_on_success', models.IntegerField()),
                ('cooldown_on_failure', models.IntegerField()),
                ('contact', models.ManyToManyField(to='gm.Contact')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='gm.Mission')),
                ('news_on_failure', models.ManyToManyField(related_name='news_on_failure', to='gm.News')),
                ('news_on_success', models.ManyToManyField(related_name='news_on_success', to='gm.News')),
                ('on_failure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_on_failure', to='gm.Stage')),
                ('on_success', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_on_success', to='gm.Stage')),
                ('skills_needed', models.ManyToManyField(to='gm.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('glory', models.IntegerField(default=0)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Character')),
                ('members', models.ManyToManyField(related_name='team_members', to='gm.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='missiongroup',
            name='the_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_group', to='gm.Stage'),
        ),
        migrations.AddField(
            model_name='character',
            name='contacts',
            field=models.ManyToManyField(to='gm.Contact'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(to='gm.Skill'),
        ),
    ]
