# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='trigger_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='on_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_on_failure', to='gm.Stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='on_success',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_on_success', to='gm.Stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='showdown',
            field=models.NullBooleanField(),
        ),
    ]
